# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: '[dependabot][github-actions] - '
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/builder"
    commit-message:
      prefix: '[dependabot][docker] - '
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/api"
      - "/types"
      - "/signatures/helpers"
      - "/cmd/traceectl"
    schedule:
      interval: "daily"
    commit-message:
      prefix: '[dependabot][gomod-security] - '
    groups:
      # Group security updates for golang dependencies
      # into a single pull request
      golang:
        applies-to: security-updates
        patterns:
          - "*"
