---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee-policies
data:
  signatures.yaml: |-
    name: signature_events
    description: traces all signature events
    defaultAction: log
    scope:
      - global
    rules:
      - event: stdio_over_socket
      - event: k8s_api_connection
      - event: aslr_inspection
      - event: proc_mem_code_injection
      - event: docker_abuse
      - event: scheduled_task_mod
      - event: ld_preload
      - event: cgroup_notify_on_release
      - event: default_loader_mod
      - event: sudoers_modification
      - event: sched_debug_recon
      - event: system_request_key_mod
      - event: cgroup_release_agent
      - event: rcd_modification
      - event: core_pattern_modification
      - event: proc_kcore_read
      - event: proc_mem_access
      - event: hidden_file_created
      - event: anti_debugging
      - event: ptrace_code_injection
      - event: process_vm_write_inject
      - event: disk_mount
      - event: dynamic_code_loading
      - event: fileless_execution
      - event: illegitimate_shell
      - event: kernel_module_loading
      - event: k8s_cert_theft
      - event: proc_fops_hooking
      - event: syscall_hooking
      - event: dropped_executable
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee-config
data:
  config.yaml: |-
    cache:
      - cache-type=mem
      - mem-cache-size=512
    perf-buffer-size: 1024
    containers: true
    healthz: true
    metrics: true
    pprof: false
    pyroscope: false
    listen-addr: :3366
    log:
        - info
    output:
        - json
        - option:parse-arguments
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:0.14.2
        imagePullPolicy: IfNotPresent
        command: 
          - /tracee/tracee
        args:
          - --policy
          - /tracee/policies
          - --config 
          - /tracee/config.yaml
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3366
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-tracee
          mountPath: /tmp/tracee
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        - mountPath: /var/run/containerd/containerd.sock
          name: containerd-sock
          readOnly: true
        - mountPath: /var/run/crio/crio.sock
          name: crio-sock
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: true
        - mountPath: /var/run/podman/podman.sock
          name: podman-sock
          readOnly: true
        - name: tracee-config
          readOnly: true
          mountPath: /tracee/config.yaml
          subPath: config.yaml
        - name: tracee-policies
          readOnly: true
          mountPath: /tracee/policies
        # NOTE: Resource consumption will vary between different use cases and
        # workload characteristics. User should monitor tracee for resource
        # consumption before enabling resource limits. Capping tracee
        # resources may cause loss of events and miss detections. Golang
        # signatures outperforms REGO signatures, use less HW resources,
        # and are preferred if that is an option.
        # resources:
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 1Gi # tracee has a 512MB in-memory events cache enabled by default
        #   requests:
        #     cpu: "1"
        #     memory: 1Gi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /tmp/tracee
        name: tmp-tracee
      - hostPath:
          path: /etc/os-release
        name: etc-os-release
      - hostPath:
          path: /var/run/containerd/containerd.sock
        name: containerd-sock
      - hostPath:
          path: /var/run/crio/crio.sock
        name: crio-sock
      - hostPath:
          path: /var/run/podman/podman.sock
        name: podman-sock
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock
      - name: tracee-config
        configMap:
          name: tracee-config
      - name: tracee-policies
        configMap:
          name: tracee-policies
