apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: tracee
    app.kubernetes.io/name: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - args:
        - --filter set=signatures
        - --output json
        - --containers
        env:
        - name: LIBBPFGO_OSRELEASE_FILE
          value: /etc/os-release-host
        image: docker.io/aquasec/tracee:0.14.2
        imagePullPolicy: IfNotPresent
        name: tracee
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp/tracee
          name: tmp-tracee
        - mountPath: /etc/os-release-host
          name: etc-os-release
          readOnly: true
        - mountPath: /var/run/containerd/containerd.sock
          name: containerd-sock
          readOnly: true
        - mountPath: /var/run/crio/crio.sock
          name: crio-sock
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: true
        - mountPath: /var/run/podman/podman.sock
          name: podman-sock
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /tmp/tracee
        name: tmp-tracee
      - hostPath:
          path: /etc/os-release
        name: etc-os-release
      - hostPath:
          path: /var/run/containerd/containerd.sock
        name: containerd-sock
      - hostPath:
          path: /var/run/crio/crio.sock
        name: crio-sock
      - hostPath:
          path: /var/run/podman/podman.sock
        name: podman-sock
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock
