name: Debug Distro Shell
on:
  workflow_dispatch:
    inputs:
      distro:
        type: choice
        description: Distro Image to Debug
        required: true
        options:
          - alma418
          - alma418-arm64
          - amzn2510
          - amzn2510-arm64
          - gke54
          - gke510
          - gke515
          - gke515-arm64
          - focal54
          - focal54-arm64
          - focal513
          - focal513-arm64
          - jammy515
          - jammy515-arm64
          - jammy519
          - jammy519-arm64
          - focal419
          - focal419-arm64
          - jammy6127
          - jammy6301
jobs:
  alma418:
    if: ${{ github.event.inputs.distro == 'alma418' }}
    runs-on:
      - graas_ami-0763bdb83bba5e638_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  alma418-arm64:
    if: ${{ github.event.inputs.distro == 'alma418-arm64' }}
    runs-on:
      - graas_ami-06152079b6b8d1f26_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  amzn2510:
    if: ${{ github.event.inputs.distro == 'amzn2510' }}
    runs-on:
      - graas_ami-0b9c1568cd5551408_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  amzn2510-arm64:
    if: ${{ github.event.inputs.distro == 'amzn2510-arm64' }}
    runs-on:
      - graas_ami-071a53e3ad06e6a7e_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  gke54:
    if: ${{ github.event.inputs.distro == 'gke54' }}
    runs-on:
      - graas_ami-07803dec079f9dab8_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  gke510:
    if: ${{ github.event.inputs.distro == 'gke510' }}
    runs-on:
      - graas_ami-03ca8e4a64be4e6e2_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  gke515:
    if: ${{ github.event.inputs.distro == 'gke515' }}
    runs-on:
      - graas_ami-0e71c360809862bd7_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  gke515-arm64:
    if: ${{ github.event.inputs.distro == 'gke515-arm64' }}
    runs-on:
      - graas_ami-0b66222a60f8f97be_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  focal54:
    if: ${{ github.event.inputs.distro == 'focal54' }}
    runs-on:
      - graas_ami-0d9d35323406a6cad_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  focal54-arm64:
    if: ${{ github.event.inputs.distro == 'focal54-arm64' }}
    runs-on:
      - graas_ami-0a241eeae02842052_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  focal513:
    if: ${{ github.event.inputs.distro == 'focal513' }}
    runs-on:
      - graas_ami-0c86a42b0f61bd86e_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  focal513-arm64:
    if: ${{ github.event.inputs.distro == 'focal513-arm64' }}
    runs-on:
      - graas_ami-07de8512322c4a33a_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy515:
    if: ${{ github.event.inputs.distro == 'jammy515' }}
    runs-on:
      - graas_ami-02f0ed24d636fa1a7_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy515-arm64:
    if: ${{ github.event.inputs.distro == 'jammy515-arm64' }}
    runs-on:
      - graas_ami-0b6d16ce9f5576b40_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy519:
    if: ${{ github.event.inputs.distro == 'jammy519' }}
    runs-on:
      - graas_ami-02ce72d6cd652cbbd_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy519-arm64:
    if: ${{ github.event.inputs.distro == 'jammy519-arm64' }}
    runs-on:
      - graas_ami-07271263d87a0e883_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_arm64c
      - EXECUTION_TYPE=LONG
    timeout-minutes: 50400
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy6127:
    if: ${{ github.event.inputs.distro == 'jammy6127' }}
    runs-on:
      - graas_ami-0469948ef83c039e9_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
  jammy6301:
    if: ${{ github.event.inputs.distro == 'jammy6301' }}
    runs-on:
      - graas_ami-05bc39f8670e0c226_${{ github.event.number }}${{ github.run_attempt }}-${{ github.run_id }}_x64c
      - EXECUTION_TYPE=LONG
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Executing Debug Shell"
        run: ./tests/remotessh.sh
