# This is a manually triggered workflow to publish aquasec/tracee-tester:latest
# container image to DockerHub. The image is used in smoke and end-to-end tests
# and is built from tests/tracee-trainer/Dockerfile. Whenever you change it
# remember to publish to DockerHub.
name: Publish tracee-tester Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Name and optionally a tag in the 'name:tag' format"
        default: "aquasec/tracee-tester:latest"
        required: false
jobs:
  deploy:
    name: Deploy the latest documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker image build --tag ${{ github.event.inputs.tag }} tests/tracee-tester
      - name: Login to docker.io registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker image push ${{ github.event.inputs.tag }}
