#
# When tag vXXX is pushed: Release Tracee
#
name: Release
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release X64 (Default)
    runs-on:
      [
        "github-self-hosted_ami-0dbd72bde72e7beae_${{ github.event.number }}-${{ github.run_id }}",
      ]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v1.13.1"
      - name: Authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
          docker login docker.io --username ${{ secrets.DOCKERHUB_USER }} --password-stdin <<<'${{ secrets.DOCKERHUB_TOKEN }}'
      - uses: imjasonh/setup-crane@e82f1b9a8007d399333baba4d75915558e9fb6a4 # v0.2
      - name: Build and Release
        run: 
          crane auth login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
          make -f builder/Makefile.release PUSH_DOCKER_REPO=aquasec/tracee
  release-arm64:
    name: Release ARM64
    # only runs after x64 released (x64 is still the "default" arch, will create the release)
    needs:
      - release
    runs-on:
      [
        "github-self-hosted_ami-0d18dadac8b80bca6_${{ github.event.number }}-${{ github.run_id }}",
      ]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      # TODO: check if sigstore/cosign-installer@main supports arm64
      - name: Authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
          docker login docker.io --username ${{ secrets.DOCKERHUB_USER }} --password-stdin <<<'${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and Release
        run: |
          crane auth login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
          make -f builder/Makefile.release PUSH_DOCKER_REPO=aquasec/tracee
