# Test signatures on CRON schedule or on demand.
name: Scheduled Signatures Test

on:
  workflow_dispatch: { }
  schedule:
    - cron: "0 0 * * *"  # every night

env:
  GO_VERSION: "1.17"
  OPA_VERSION: "v0.35.0"

jobs:
  e2e-test-signatures:
    name: "[E2E] Test Signatures"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore Go modules from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: ${{ env.GO_VERSION }}
          opa-version: ${{ env.OPA_VERSION }}
      - name: Buld tracee trainer
        run: |
          make -f tests/Makefile docker-build-tracee-trainer
      - name: Build tracee-nocore
        run: |
          make -f builder/Makefile.tracee-container build-alpine-tracee-nocore
      - name: Install BPF
        run: |
          make -f Makefile.one install-bpf-nocore
      - name: Run tests
        run: |
          go test -v -run "TestTraceeSignatures" ./tests/tracee_test.go \
            -tracee-image-ref "tracee-nocore:latest"
